name: Deploy Room Manager

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  cd:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Room Manager example
        run: docker build -f examples/room-manager/Dockerfile -t gh-runner-room-manager .

      - name: Clean up the previous Room Manager container
        run: docker rm -f gh-runner-room-manager

      - name: Run Room Manager example
        run: |
          docker run -d -p 8080:8080 \
          --name gh-runner-room-manager \
          --restart always \
          -e PORT=8080 \
          -e PEERLESS_PURGE_TIMEOUT=600 \
          -e FISHJAM_URL=${{ secrets.ROOM_MANAGER_FISHJAM_URL }} \
          -e FISHJAM_SERVER_TOKEN=${{ secrets.ROOM_MANAGER_FISHJAM_SERVER_TOKEN }} \
          -e WEBHOOK_URL=${{ secrets.ROOM_MANAGER_WEBHOOK_URL }} \
          gh-runner-room-manager
